// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xamatxftmpfwupokvqjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbWF0eGZ0bXBmd3Vwb2t2cWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NjcwMzIsImV4cCI6MjA3MzE0MzAzMn0.I7pH75fg06gcA-Q6-0B-Sir0YCfSkfkY2OpUwujcmNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});